### ISSUE TITLE
should add some notes for MSYS2 users

### ISSUE THREAD

**Issue by ookiineko** [svoboda18/magiskboot#2]
nice work

@affggh told me this project doesn't build on MSYS2 with the MINGW64 environment (see also the [document](https://www.msys2.org/docs/environments/) here about these "environments" on MSYS2)
so i found out it's mainly because of the C and C++ standard library this project uses
when building in the MINGW64 environment, i had basically got these errors:
1. some headers are missing (it turned out to be a C++ standard library issue, after installing the libc++ package (yes in the MINGW64 environment it uses the libstdc++ as the default C++ standard library and clang++ uses that too, so the libc++ isn't installed by default) it worked)
2. some functions are not declared (i had to include some extra headers in some source files to fix this. i think it is because of the default C++ standard library again (probably the compiler is not configured to use any C++ standard library other than libstd++ in this environment))
3. some symbols are undefined when linking (it happens when you try to do static linking for any C++ program that uses libc++ and the new/delete operator, so maybe the compiler isn't configured to work in this case (dynamic linking works just fine))

when i try to build the project in the UCRT64 environment (this environment uses UCRT as the default C standard library, but still uses libstdc++ as the default C++ standard library), i still get the third error

finally, i am able to successfully build and run magiskboot without any problem when i use the CLANG64 environment (since it uses libc++ as the default C++ standard library)

**Comment by ookiineko** [comment]
sorry for my bad english

**Comment by ookiineko** [comment]
![image](https://user-images.githubusercontent.com/103345643/226729551-761760ea-cd4a-493d-8489-83e0af0c2bc9.png)

**Comment by ookiineko** [comment]
also the binary size fyi:
![image](https://user-images.githubusercontent.com/103345643/226730662-017e075d-2f86-4bef-8de3-64d3981a62c2.png)

**Comment by ookiineko** [comment]
> finally, i am able to successfully build and run magiskboot without any problem when i use the CLANG64 environment (since it uses libc++ as the default C++ standard library)

just installing the `mingw-w64-clang-x86_64-clang` package for the clang compiler (and it will also install llvm & libc++) is enough for me

**Comment by svoboda18** [comment]
Hey

Thats correct, CLANG64 env is the only one that uses `libc++` as the standard C++ library which indeed this project is based on and the MINGW64/UCRT64 has GCC headers/libs if I had to guess which causes all of those errors, and about the binary size, that's the correct size of the dynamically linked binary.

Hence, updated the README in 3e003d43a4a73751cc64d086c0c7de594b66e6fb, which should make this issue as closed.
