### ISSUE TITLE
The latest binary doesn't works

### ISSUE THREAD

**Issue by DeadPool-4422** [svoboda18/magiskboot#4]
This is the error i get when i try to run the latest binary although the previous one works as expected

####Latest Binary######

~\Downloads\magiskboot
❯ .\magiskboot.exe
Program 'magiskboot.exe' failed to run: The file or directory is corrupted and unreadableAt line:1 char:1
+ .\magiskboot.exe
+ ~~~~~~~~~~~~~~~~.
At line:1 char:1
+ .\magiskboot.exe
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

####Previous Binary######

~\Downloads\magiskboot(1)
❯ .\magiskboot.exe
MagiskBoot - Boot Image Modification Tool

Usage: C:\Users\Hari\Downloads\magiskboot(1)\magiskboot.exe <action> [args...]

Supported actions:
  unpack [-n] [-h] <bootimg> [outdir]
    Unpack <bootimg> to its individual components, each component to
    a file with its corresponding file name in the current directory.
    Supported components: kernel, kernel_dtb, ramdisk.cpio, second,
    dtb, extra, and recovery_dtbo.
    By default, each component will be automatically decompressed
    on-the-fly before writing to the output file.
    If '-n' is provided, all decompression operations will be skipped;
    each component will remain untouched, dumped in its original format.
    If '-h' is provided, the boot image header information will be
    dumped to the file 'header', which can be used to modify header
    configurations during repacking.
    Return values:
    0:valid    1:error    2:chromeos

**Comment by svoboda18** [comment]
sorry for the inconvenience, the [1.0-3](https://github.com/svoboda18/magiskboot/releases/tag/1.0-3) release has been updated with correct asset.
