### ISSUE TITLE
How to use cpio patch ?

### ISSUE THREAD

**Issue by Mitezuss** [svoboda18/magiskboot#5]
Hi, nice port. Thank

Have a question, how set the KEEPFORCEENCRYPT or KEEPVERITY ? (On Windows. By default is false ?)

**Comment by svoboda18** [comment]
yes, they are set to false unless you define them as "true", as coded here:
https://github.com/svoboda18/magiskboot/blob/2ae1419085bb24076b4b3e1c0143d86b21c01788/ramdisk.cpp#L26-L28

which is used as:
https://github.com/svoboda18/magiskboot/blob/2ae1419085bb24076b4b3e1c0143d86b21c01788/ramdisk.cpp#L31-L33

here is an example how to set KEEPFORCEENCRYPT, run in cmd: `set KEEPFORCEENCRYPT=true`
